### ISSUE TITLE
vector-like SMID types

### ISSUE THREAD

**Issue by hartsantler** [Cincinesh/tue#20]
in `tue/simd.hpp` there is several SMID types defined like `float32x4`.
and in 'tue/vec.hpp `it defines `fvec4`, which auto wraps the SMID type `float32x4` if intrinsics are available?
or to use SMID, the `float32x4`, and other dedicated types are required?

It might be simpler if the SMID types were more vector like.

With a vector type, its easy to get the first element `myvec[0]`, but with SMID types you have to do `myvec.data()[0]`

**Comment by Cincinesh** [comment]
`fvec4` never wraps `float32x4`. While they have the same data layout, they're meant for different use cases. Accessing individual elements of SIMD intrinsics is a relatively slow operation that, if done frequently, negates the value of using SIMD intrinsics. You need to do it occasionally, but it's intentionally difficult as you describe.
