### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by nuzrub** [Cincinesh/tue#22]
Hey! I've found this project and was amazed by finally founding a vector library that understands SIMD properly. However, I noticed that the last commit added was about 2 years ago and that there is quite a bunch of commits hanging on the developing branch.

Therefore, I ask, was the project closed? was it moved to a different place/name?
If it was indeed closed, why?
Finally, is it ready for production use? was it used on a real application with success?

Thank you :)

**Comment by Cincinesh** [comment]
Unfortunately, I simply haven't been interested in working on it. This is still its home, and I may return to it some day, but I don't have any plans to right now.

I don't personally know of any production users.
